### ISSUE TITLE
Missing several dependencies for conda-store-server

### ISSUE THREAD

**Issue by Adam-D-Lewis** [conda-forge/conda-store-feedstock#36]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Comparing https://github.com/conda-forge/conda-store-feedstock/blob/7e2769ccb0d85a2572bae83dfd04fd5db224229e/recipe/meta.yaml#L56 
with 

https://github.com/conda-incubator/conda-store/blob/b40b7e3ee910668d54fb29bf75eca8ddd36eb877/conda-store-server/pyproject.toml#L34 

I see that several dependencies are missing (conda-lock, conda-pack, etc.).  This causes https://github.com/conda-incubator/conda-store/issues/818.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by trallard** [comment]
Known issue, originally planned to be fixed through https://github.com/conda-incubator/conda-store/pull/801/files#diff-2798205d73e8179f7cd9fbc9da2c6446c88c25f80180a50971c37ea9c345c8f5 

ended up being fixed in https://github.com/conda-incubator/conda-store/pull/827 so this should be in the upcoming release

**Comment by trallard** [comment]
Completed so will go ahead and close
